/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SystemAdminPanel;

import Business.Business;
import Department.College;
import Department.Department;
import HODProfile.Hod;
import UserAccounts.UserAccountDirectory;
import UserAccounts.UserAccounts;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tanujkodali
 */
public class DepartmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DepartmentJPanel
     */
    Business business;
    UserAccounts userAccounts;
    UserAccountDirectory userAccountDirectory;
    DefaultTableModel deptTableModel;
    Department dept;
   
    
    
    public DepartmentJPanel() {
        initComponents();
    }
    
    
    public DepartmentJPanel(Business business, UserAccounts userAccounts,Department dept) {
         initComponents();
        this.business = business;
        this.userAccounts = userAccounts;
        this.dept = dept;
        this.deptTableModel = (DefaultTableModel) DeptjTable.getModel();
        displaydept();
       
      }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldDeptName = new javax.swing.JTextField();
        createDeptBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DeptjTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 180, 0));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Department");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel4.setText("Department Name:");

        createDeptBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        createDeptBtn.setText("Create");
        createDeptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDeptBtnActionPerformed(evt);
            }
        });

        DeptjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Department ID", "Department Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DeptjTable);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createDeptBtn)
                    .addComponent(fieldDeptName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(693, 693, 693)
                .addComponent(jButton2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4))
                            .addComponent(fieldDeptName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(createDeptBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jButton2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createDeptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDeptBtnActionPerformed
        // TODO add your handling code here:
    UserAccountDirectory User = this.business.getUserAccountDirectory();
        
        
        
        String depName = fieldDeptName.getText();
       
        /*
        UserAccountDirectory userDir = this.dept.getUserAccountDirectory();
        
        if(college.isBlank() || depId.isBlank() || depName.isBlank()){
            JOptionPane.showMessageDialog(null,"Please enter details in all fields");
        } else {
            if(userDir.accountExists(username, password, name)){
            JOptionPane.showMessageDialog(null, "Account already exists!!!");
        }
        */
        
        UserAccountDirectory userDir = this.business.getUserAccountDirectory();
        Department dept = new Department("Department-");
        if( depName.isBlank()){
            JOptionPane.showMessageDialog(null,"Please enter details in all fields");
        } else {
            this.business.getDepartmentDirectory().createDepartment(dept.getDeptId(), depName);
            JOptionPane.showMessageDialog(null, "Department Created!!!");
        }
        displaydept();

    }//GEN-LAST:event_createDeptBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int selectedRow  =  DeptjTable.getSelectedRow();
        
        if(selectedRow >= 0){
            //delete the object
            this.dept = (Department) DeptjTable.getValueAt(selectedRow,0);
            this.business.getDepartmentDirectory().deleteApplicant(dept.getDeptId());

        }
        displaydept();
    
    }//GEN-LAST:event_jButton2ActionPerformed

   public void displaydept(){
        
       deptTableModel.setRowCount(0);
        for(Department dept: this.business.getDepartmentDirectory().getDepartmentList()){

            
            
            Object[] row = new Object[10];
            
            row[0] = dept;
            row[1] = dept.getName();
        
               
            deptTableModel.addRow(row);
            
        }
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DeptjTable;
    private javax.swing.JButton createDeptBtn;
    private javax.swing.JTextField fieldDeptName;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
