/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SystemAdminPanel;

import Business.Business;
import Department.Department;
import EmployeeProfile.Employee;
import HODProfile.Hod;
import UserAccounts.UserAccountDirectory;
import UserAccounts.UserAccounts;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tanujkodali
 */
public class EmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeJPanel
     */
    
    Business business;
    UserAccounts userAccounts;
    Department dept;
    UserAccountDirectory userAccountDirectory;
    DefaultTableModel empTableModel;

    public EmployeeJPanel() {
        initComponents();
    }
    
    public EmployeeJPanel(Business business, UserAccounts userAccount,Department dept) {
        initComponents();
        
        this.business = business;
        this.userAccounts = userAccount;
        this.dept = dept;
        this.empTableModel = (DefaultTableModel) empTable.getModel();
        displayDepartment();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        fieldExp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fieldUser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fieldPass = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        deptComboBox = new javax.swing.JComboBox<>();
        createBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 119, 218));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Employee");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 17, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel4.setText("Employee Name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel6.setText("Employee Expereince:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));
        add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 123, -1));
        add(fieldExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 124, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel7.setText("Username:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));
        add(fieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 124, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel8.setText("Password:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        fieldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPassActionPerformed(evt);
            }
        });
        add(fieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 124, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setText("Department Name:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 116, -1, -1));

        add(deptComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 123, -1));

        createBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Department ", "Employer ID", "Name", "Experience"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(empTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 420, 300));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPassActionPerformed

    
    public void displayDepartment(){
      deptComboBox.removeAllItems();
        for(Department a: this.business.getDepartmentDirectory().getDepartmentList()){
           deptComboBox.addItem(a.getName());
        }
    }
    
    public void display(){
        empTableModel.setRowCount(0);
        for(Employee emp: this.business.getEmployeeDirectory().getEmployeeList()){
        //UserAccounts u = this.business.getUserAccountDirectory().findHodbyId(hod.getId());
            
            
            Object[] row = new Object[10];
           
            //UserAccounts u = this.business.getUserAccountDirectory().findbyId(hod.getId());

            row[0] = emp.getDeptName();
            row[1] = emp.getEmpId();
            row[2] = emp.getName();
            row[3] = emp.getExperience();
            //row[4] = u.getUsername();
            //row[5] = u.getPassword();
            
            
            empTableModel.addRow(row);
            
        }
    }
    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        
        
        String name= fieldName.getText();
        String exp= fieldExp.getText();
        String username = fieldUser.getText();
        String password = fieldPass.getText();
        String deptName = String.valueOf(deptComboBox.getSelectedItem());
        
        UserAccountDirectory userDir = this.business.getUserAccountDirectory();

        if( name.isBlank() ||exp.isBlank()||username.isBlank()||password.isBlank()){
            JOptionPane.showMessageDialog(null,"Please enter details in all fields");
        } else
        if(userDir.accountExists(username, password, "Employer")){
            JOptionPane.showMessageDialog(null, "Account already exists!!!");
        }
        else {
            UserAccounts user = this.business.getUserAccountDirectory().createUser(username, password, "Employer", deptName);
            this.business.getEmployeeDirectory().createEmployee(name, user.getEmployerId(), Double.valueOf(exp), deptName);
            JOptionPane.showMessageDialog(null, "Account Created!!!");
            //populate();
        }
        
        display();
    }//GEN-LAST:event_createBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JComboBox<String> deptComboBox;
    private javax.swing.JTable empTable;
    private javax.swing.JTextField fieldExp;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPass;
    private javax.swing.JTextField fieldUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
