/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminPanel;

import Business.Business;
import Department.Department;
import EmployeeProfile.Employee;
import UserAccounts.UserAccounts;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hi
 */

public class ExperienceReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExperienceReportJPanel
     */
    
    Business business;
    UserAccounts userAccounts;
    Department dept;
    DefaultTableModel expTableModel;
    
    public ExperienceReportJPanel() {
        initComponents();
    }
    
    public ExperienceReportJPanel(Business business, UserAccounts userAccounts, Department dept) {
        initComponents();
        
        this.business = business;
        this.userAccounts = userAccounts;
        this.dept = dept;
        this.expTableModel = (DefaultTableModel) expTable.getModel();
        
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        expTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Experience Report");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 49, -1, -1));

        expTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Department", "Employer", "Experience"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(expTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 113, 351, 249));
    }// </editor-fold>//GEN-END:initComponents

    public void display(){
        ArrayList<Employee> emp = this.business.getEmployeeDirectory().getEmployeeList();
        expTableModel.setRowCount(0);
        if(emp.size()>0){
            for(Employee e: emp){
                
                    Object row[] = new Object[15];
                    row[0] = e.getDeptName();
                    row[1] = e.getName();
                    row[2] = e.getExperience();
                    
                    expTableModel.addRow(row);
                
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable expTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
