/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdminPanel;

import Business.Business;
import Department.Department;
import HODProfile.Hod;
import Role.HOD;
import UserAccounts.UserAccountDirectory;
import UserAccounts.UserAccounts;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tanujkodali
 */
public class HodJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HodJPanel
     */
    Business business;
    UserAccounts userAccounts;
    UserAccountDirectory userAccountDirectory;
    DefaultTableModel HodTableModel;
    Department dept;
    Hod hod;

    
    public HodJPanel() {
        initComponents();
    }
    
     public HodJPanel(Business business, UserAccounts userAccounts,Department dept) {
         initComponents();
        this.business = business;
        this.userAccounts = userAccounts;
        this.dept = dept;
        this.HodTableModel = (DefaultTableModel) HodTable.getModel();
        
        displayDepartment();
        displayHod();
     
      }

   
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        deptComboBox = new javax.swing.JComboBox();
        fieldName = new javax.swing.JTextField();
        fieldExp = new javax.swing.JTextField();
        fieldUser = new javax.swing.JTextField();
        fieldPass = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HodTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(135, 219, 220));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("HOD");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Department Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 83, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("HOD Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 129, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("HOD Experience:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("UserName;");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("Password:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        add(deptComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 79, 147, -1));
        add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 124, 147, -1));
        add(fieldExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 147, -1));
        add(fieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 147, -1));
        add(fieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 147, -1));

        createBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        HodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Department Name", "HOD Name", "Hod ID", "HOD Experience"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(HodTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 600, 320));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

     public void displayDepartment(){
      deptComboBox.removeAllItems();
        for(Department a: this.business.getDepartmentDirectory().getDepartmentList()){
           deptComboBox.addItem(a.getName());
        }
    }
    
                
    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        String name = fieldName.getText();
        String exp= fieldExp.getText();
        String username = fieldUser.getText();
        String password = fieldPass.getText();
        String deptName = String.valueOf(deptComboBox.getSelectedItem());
        
        UserAccountDirectory userDir = this.business.getUserAccountDirectory();
          
        if( name.isBlank() ||exp.isBlank()||username.isBlank()||password.isBlank()){
            JOptionPane.showMessageDialog(null,"Please enter details in all fields");
        } else
        if(userDir.accountExists(username, password, "Department HOD")){
            JOptionPane.showMessageDialog(null, "Account already exists!!!");
        } else {
                  UserAccounts user = this.business.getUserAccountDirectory().createUser(username, password, "Department HOD", deptName);
            this.business.getHodDirectory().createHod(name, user.getHodId(), user.getDeptName(), Double.valueOf(exp));
              JOptionPane.showMessageDialog(null, "Account Created!!!");
        }
        displayHod();
        
        
    }//GEN-LAST:event_createBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       int selectedRow  =  HodTable.getSelectedRow();
        
        if(selectedRow >= 0){
            //delete the object
            this.hod = (Hod) HodTable.getValueAt(selectedRow,0);
           this.business.getHodDirectory().deletehod(hod.getId());

        }
        displayHod();
        
            
    }//GEN-LAST:event_jButton1ActionPerformed
   
      
     public void displayHod(){
        
       HodTableModel.setRowCount(0);
        for(Hod hod: this.business.getHodDirectory().getHodList()){
        //UserAccounts u = this.business.getUserAccountDirectory().findHodbyId(hod.getId());
            
            
            Object[] row = new Object[10];
           
            //UserAccounts u = this.business.getUserAccountDirectory().findbyId(hod.getId());

            row[0] = hod;
            row[1] = hod.getName();
            row[2] = hod.getId();
            row[3] = hod.getExperience();
            //row[4] = u.getUsername();
            //row[5] = u.getPassword();
            
            
            HodTableModel.addRow(row);
            
        }
     }
    
    
    
    
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HodTable;
    private javax.swing.JButton createBtn;
    private javax.swing.JComboBox deptComboBox;
    private javax.swing.JTextField fieldExp;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPass;
    private javax.swing.JTextField fieldUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
