/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Faculty;

import Business.Business;
import Department.Department;
import UI.HeadOfDepartment.ManageCourseScheduleJPanel;
import UI.MainJFrame;
import UserAccounts.UserAccounts;

/**
 *
 * @author 91730
 */
public class FacultyJFrame extends javax.swing.JFrame {

    /**
     * Creates new form FacultyJFrame
     */
    
    Business business;
    UserAccounts userAccounts;
    Department dept;
    
    public FacultyJFrame() {
        initComponents();
    }

    public FacultyJFrame(Business business, UserAccounts userAccounts, Department dept) {
        initComponents();
        this.setVisible(true);
        this.business = business;
        this.userAccounts = userAccounts;
        this.dept = dept;
        facultyDepartment.setText(userAccounts.getDeptName());
        facultyId.setText(userAccounts.getFacultyId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        facultyDepartment = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        registration = new javax.swing.JButton();
        feedback = new javax.swing.JButton();
        facultyId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Faculty");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 40, 20));

        facultyDepartment.setText("jLabel2");
        jPanel1.add(facultyDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 20));

        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        registration.setText("View Course Registrations");
        registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationActionPerformed(evt);
            }
        });
        jPanel1.add(registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        feedback.setText("View Course Feedback");
        feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackActionPerformed(evt);
            }
        });
        jPanel1.add(feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 210, 150, -1));

        facultyId.setText("jLabel2");
        jPanel1.add(facultyId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 20));

        jSplitPane1.setLeftComponent(jPanel1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainJFrame main = new MainJFrame(this.business,this.userAccounts, this.dept);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ViewCourseRegistrationsJPanel(this.business,this.userAccounts, this.dept));
    }//GEN-LAST:event_registrationActionPerformed

    private void feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ViewCourseFeedbackJPanel(this.business,this.userAccounts, this.dept));
    }//GEN-LAST:event_feedbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel facultyDepartment;
    private javax.swing.JLabel facultyId;
    private javax.swing.JButton feedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton registration;
    // End of variables declaration//GEN-END:variables
}
