/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Faculty;

import Business.Business;
import CourseCatalog.Course;
import Department.Department;
import FacultyProfile.Faculty;
import Student.Student;
import UserAccounts.UserAccounts;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 91730
 */
public class ViewCourseRegistrationsJPanel extends javax.swing.JPanel {

    private Business business;
    private UserAccounts userAccounts;
    private Department dept;
    DefaultTableModel viewTableModel;
    
    /**
     * Creates new form CourseRegisteredAndFeedbackJPanel
     */
    public ViewCourseRegistrationsJPanel() {
        initComponents();
        
    }

    ViewCourseRegistrationsJPanel(Business business, UserAccounts userAccounts, Department dept) {
        initComponents();
        this.setVisible(true);
        this.business = business;
        this.userAccounts = userAccounts;
        this.dept = dept;
        this.viewTableModel = (DefaultTableModel) courseRegistration.getModel();
        displayRegisteredCourses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        courseRegistration = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        courseRegistration.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Id", "Course Name", "Semester", "Faculty", "Student Id", "Student Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(courseRegistration);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 640, 210));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Registrations");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void displayRegisteredCourses() {
        
        ArrayList<Student> student =  this.business.getStudentDirectory().getStudentList();
        ArrayList<Faculty> faculty = this.business.getFacultyDirectory().getFacultyList();
        
        viewTableModel.setRowCount(0);
        
        for (Student s : student){
            if(s.getDeptName().equals(userAccounts.getDeptName())){
                System.out.println("Here1");
                
                for (Course c: s.getCourseSeat()){
                    for ( Faculty f : faculty){
                        if(f.getName().equals(c.getFaculty().getName()))
                        {
                            System.out.println(f.getId());
                            System.out.println(c.getName());
                            System.out.println(userAccounts.getFacultyId());
                            if(f.getId().equals(userAccounts.getFacultyId())){
                                System.out.println("Inside loop");
                                System.out.println(c.getName());
                                Object row[] = new Object[6];
                                row[0]=c;
                                row[1]=c.getName();
                                row[2]=c.getSem().getSemName();
                                row[3]=c.getFaculty().getName();
                                row[4]=s.getId();
                                row[5]=s.getName();
                                viewTableModel.addRow(row);
                                break;
                            }
                        }
                        else{
                            System.out.println("No Registrations under current Faculty");
                        }   
                    }
                }
            }
//                    System.out.println(c.getFaculty().getId());
//                    System.out.println(userAccounts.getFacultyId());
//                    if(c.getFaculty().getId()==userAccounts.getFacultyId()){
//                        System.out.println("Here1");
//                        Object row[] = new Object[6];
//                        row[0]=c;
//                        row[1]=c.getName();
//                        row[2]=c.getSem().getSemName();
//                        row[3]=c.getFaculty().getName();
//                        row[4]=s.getId();
//                        row[5]=s.getName();
//                        viewTableModel.addRow(row);
//                    }
//                    else{
//                        System.out.println("No Registrations under current Faculty");
//                    }
//                }
//            }
            else{
                System.out.println("Empty List1");
            }
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable courseRegistration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
