/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Faculty;

import Business.Business;
import CourseCatalog.Course;
import Department.Department;
import FacultyProfile.Faculty;
import Student.Student;
import UserAccounts.UserAccounts;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 91730
 */
public class ViewCourseFeedbackJPanel extends javax.swing.JPanel {

    private Business business;
    private UserAccounts userAccounts;
    private Department dept;
    private DefaultTableModel viewTableModel;

    /**
     * Creates new form ViewCourseFeedbackJPanel
     */
    public ViewCourseFeedbackJPanel() {
        initComponents();
    }

    ViewCourseFeedbackJPanel(Business business, UserAccounts userAccounts, Department dept) {
        initComponents();
        this.setVisible(true);
        this.business = business;
        this.userAccounts = userAccounts;
        this.dept = dept;
        this.viewTableModel = (DefaultTableModel) courseFeedback.getModel();
        displayFeedbackTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        courseFeedback = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        courseFeedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Id", "Course Name", "Semester", "Rating", "Comment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(courseFeedback);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 640, 210));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Feedback");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void displayFeedbackTable() {
        
        ArrayList<Student> student =  this.business.getStudentDirectory().getStudentList();
        ArrayList<Faculty> faculty = this.business.getFacultyDirectory().getFacultyList();
        
        viewTableModel.setRowCount(0);
        
        for (Student s : student){
            if(s.getDeptName().equals(userAccounts.getDeptName())){
                
                for (Course c: s.getCourseSeat()){
                    for ( Faculty f : faculty){
                        if(f.getName().equals(c.getFaculty().getName()))
                        {
                            System.out.println(f.getId());
                            System.out.println(c.getName());
                            System.out.println(userAccounts.getFacultyId());
                            if(f.getId().equals(userAccounts.getFacultyId()) && c.getFeedback().getFeedbackRating()!=0){
                                System.out.println("Inside");
                                System.out.println(c.getName());
                                Object row[] = new Object[5];
                                row[0]=c;
                                row[1]=c.getName();
                                row[2]=c.getSem().getSemName();
                                row[3]=c.getFeedback().getFeedbackRating();
                                row[4]=c.getFeedback().getFeedbackComment();
                                viewTableModel.addRow(row);
                                break;
                        }
                        }
                    else{
                        System.out.println("Feedback not added for any course");
                    }
                }
            }
            }
            else{
                System.out.println("Empty List1");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable courseFeedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
