/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Student;

import Business.Business;
import Department.Department;
import Employment.Employment;
import UserAccounts.UserAccounts;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hi
 */
public class ApplyJobsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ApplyJobsJPanel
     */
    Business business;
    UserAccounts userAccounts;
    Department dept;
    DefaultTableModel jobTableModel;

    public ApplyJobsJPanel() {
        initComponents();
    }
    
    public ApplyJobsJPanel(Business business, UserAccounts userAccounts, Department dept) {
        initComponents();
        
        this.business = business;
        this.userAccounts = userAccounts;
        this.dept = dept;
        this.jobTableModel = (DefaultTableModel) jobTable.getModel();
        
        displayDept();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        deptComboBox = new javax.swing.JComboBox();
        jobComboBox = new javax.swing.JComboBox();
        applyBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jobTable = new javax.swing.JTable();
        showBtn = new javax.swing.JButton();
        showJobsBtn = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(240, 190, 219));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Apply For Jobs");

        jLabel2.setText("Select Department:");

        jLabel3.setText("Select Job:");

        applyBtn.setText("Apply");
        applyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyBtnActionPerformed(evt);
            }
        });

        jobTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Department Name", "Employer ", "Job ID", "Job Role", "Job Price", "Job Status", "Job Descriptin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jobTable);

        showBtn.setText("Show Job Details");
        showBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBtnActionPerformed(evt);
            }
        });

        showJobsBtn.setText("Show Jobs");
        showJobsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showJobsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(deptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(showJobsBtn)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jobComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(showBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(339, 339, 339)
                                .addComponent(applyBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel1)))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showJobsBtn)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jobComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(showBtn))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(applyBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBtnActionPerformed
        // TODO add your handling code here:

       ArrayList<Employment> emps = this.business.getJobRequestDirectory().getEmploymentList();
        
        if(emps.size()>0){
            jobTableModel.setRowCount(0);
            
            for(Employment e: emps){
                if(e.getRole().equals(jobComboBox.getSelectedItem())){
                Object row[] = new Object[10];
                
                row[0] = e;
                row[1] = e.getEmployerName();
                row[2] = e.getEmploymentId();
                row[3] = e.getRole();
                row[4] = e.getJobPrice();
                row[5] = e.getStatus();
                row[6] = e.getJobDesc();
                
                
                jobTableModel.addRow(row);
            }
          }
        }
    }//GEN-LAST:event_showBtnActionPerformed

    public void displayJobs(){
        ArrayList<Employment> emps = this.business.getJobRequestDirectory().getEmploymentList();
        
        if(emps.size()>0){
            jobTableModel.setRowCount(0);
            
            for(Employment e: emps){
                if(e.getRole().equals(jobComboBox.getSelectedItem())){
                Object row[] = new Object[10];
                
                row[0] = e;
                row[1] = e.getEmployerName();
                row[2] = e.getEmploymentId();
                row[3] = e.getRole();
                row[4] = e.getJobPrice();
                row[5] = e.getStatus();
                row[6] = e.getJobDesc();
                
                
                jobTableModel.addRow(row);
            }
          }
        }
    }
    private void showJobsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showJobsBtnActionPerformed
        // TODO add your handling code here:
        
        jobComboBox.removeAllItems();
      for(Employment e: this.business.getJobRequestDirectory().getEmploymentList()){
          if(e.getDeptName().equals(deptComboBox.getSelectedItem())){
              jobComboBox.addItem(e.getRole());
          }
      }
    }//GEN-LAST:event_showJobsBtnActionPerformed

    private void applyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyBtnActionPerformed
        // TODO add your handling code here:
        /*
        int selectedRow = rentTable.getSelectedRow();
        
        RentalRequest r = (RentalRequest) rentTable.getValueAt(selectedRow, 0);
        
        if(r.getStatus().equals("Accept")){
            r.setStatus("Rented");
            r.getBook().setIsAvailable("no");
        } else if(r.getStatus().equals("Rejected")){
            JOptionPane.showMessageDialog(null, "Rental Request has been rejected");
        } else {
            JOptionPane.showMessageDialog(null, "Rental Request is in process!");
        }    
        */
        
        int selectedRow = jobTable.getSelectedRow();
        
        Employment emp =(Employment) jobTable.getValueAt(selectedRow, 0);
        
        //if((emp.getStatus().equals("Open") && emp.getBackendStatus().equals("Open")) || (emp.getStatus().equals("Open") && emp.getBackendStatus().equals("Applied"))){
            //emp.setStatus("Applied");
        if(emp.getStatus().equals("Open")){
            emp.setBackendStatus("Applied");
            JOptionPane.showMessageDialog(null, "Your application has been sent");
            emp.setStudentId(userAccounts.getAccountId());
        } else if (emp.getStatus().equals("Closed")){
            JOptionPane.showMessageDialog(null, "You cannot apply to this job");
        } 

        displayJobs();
    }//GEN-LAST:event_applyBtnActionPerformed

    public void displayDept(){
      deptComboBox.removeAllItems();
      for(Department d: this.business.getDepartmentDirectory().getDepartmentList()){
          deptComboBox.addItem(d.getName());
      }
      
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyBtn;
    private javax.swing.JComboBox deptComboBox;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jobComboBox;
    private javax.swing.JTable jobTable;
    private javax.swing.JButton showBtn;
    private javax.swing.JButton showJobsBtn;
    // End of variables declaration//GEN-END:variables
}
