/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Student;

import Business.Business;
import Department.Department;
import UserAccounts.UserAccounts;

/**
 *
 * @author hi
 */
public class RegisterClassesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterClassesJPanel
     */
    Business business;
    UserAccounts userAccounts;
    Department dept;
    
    public RegisterClassesJPanel() {
        initComponents();
    }
    
    public RegisterClassesJPanel(Business business, UserAccounts userAccounts, Department dept) {
        initComponents();
        
        this.business = business;
        this.userAccounts = userAccounts;
        this.dept = dept;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
