/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.EmployerJPanel;

import Business.Business;
import Department.Department;
import Employment.Employment;
import Employment.EmploymentDirectory;
import UserAccounts.UserAccountDirectory;
import UserAccounts.UserAccounts;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hi
 */
public class PostJobsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PostJobsJPanel
     */
    
    Business business;
    UserAccounts userAccounts;
    UserAccountDirectory userAccountDirectory;
    DefaultTableModel jobTableModel;
    Department dept;

    public PostJobsJPanel() {
        initComponents();
    }
    
    public PostJobsJPanel(Business business, UserAccounts userAccounts,Department dept) {
        initComponents();
        
        this.business = business;
        this.userAccounts = userAccounts;
        this.dept = dept;
        this.jobTableModel = (DefaultTableModel) jobTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldJobId = new javax.swing.JTextField();
        fieldJobName = new javax.swing.JTextField();
        fieldPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jobTable = new javax.swing.JTable();
        fieldJobDesc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(186, 160, 191));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("POST JOBS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 25, -1, -1));

        jLabel2.setText("Job ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 90, -1, -1));

        jLabel3.setText("Job Role:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 137, -1, -1));

        jLabel4.setText("Job Description:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel5.setText("Price per hour:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 187, -1, -1));
        add(fieldJobId, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 87, 98, -1));
        add(fieldJobName, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 134, 98, -1));
        add(fieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 184, 98, -1));

        jobTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Department", "Employer", "Job ID", "Job Role", "Price/hour", "Job Status", "Job Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jobTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 470, 210));
        add(fieldJobDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 100, -1));

        jButton1.setText("Post Job");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String jobId = fieldJobId.getText();
        String jobName = fieldJobName.getText();
        String jobDesc = fieldJobDesc.getText();
        String jobPrice = fieldPrice.getText();
        
        
        EmploymentDirectory jobReq = this.business.getJobRequestDirectory();
        Employment emp = new Employment();
        
        jobReq.createJobs(jobId, jobName, userAccounts.getDeptName() ,userAccounts.getAccountId(), "Open" ,Double.valueOf(jobPrice),jobDesc,"Open");
        displayJobs();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void displayJobs(){
        ArrayList<Employment> emps = this.business.getJobRequestDirectory().getEmploymentList();
        
        if(emps.size()>0){
            jobTableModel.setRowCount(0);
            
            for(Employment e: emps){
                if(e.getDeptName().equals(userAccounts.getDeptName())){
                Object row[] = new Object[10];
                
                row[0] = e;
                row[1] = e.getEmployerName();
                row[2] = e.getEmploymentId();
                row[3] = e.getRole();
                row[4] = e.getJobPrice();
                row[5] = e.getStatus();
                row[6] = e.getJobDesc();

                jobTableModel.addRow(row);
            }
          }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldJobDesc;
    private javax.swing.JTextField fieldJobId;
    private javax.swing.JTextField fieldJobName;
    private javax.swing.JTextField fieldPrice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jobTable;
    // End of variables declaration//GEN-END:variables
}
