/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.EmployerJPanel;

import Business.Business;
import Department.Department;
import Employment.Employment;
import UserAccounts.UserAccountDirectory;
import UserAccounts.UserAccounts;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hi
 */
public class RecruitStudentsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RecruitStudentsJPanel
     */
    
    Business business;
    UserAccounts userAccounts;
    UserAccountDirectory userAccountDirectory;
    Department dept;
    DefaultTableModel jobTableModel;
    

    public RecruitStudentsJPanel() {
        initComponents();
    }
    
    public RecruitStudentsJPanel(Business business, UserAccounts userAccount,Department dept) {
        initComponents();
        
        this.business = business;
        this.userAccounts = userAccount;
        this.dept = dept;
        this.jobTableModel = (DefaultTableModel) jobTable.getModel();
        
        display();
    }

    public void display(){
        ArrayList<Employment> jobs = this.business.getJobRequestDirectory().getEmploymentList();
        
        if(jobs.size()>0){
            for(Employment e: jobs){
                if(e.getDeptName().equals(userAccounts.getDeptName())){
                    Object row[] = new Object[15];
                    row[0] = e;
                    row[1] = e.getStudentId();
                    row[2] = e.getEmploymentId();
                    row[3] = e.getRole();
                    row[4] = e.getJobPrice();
                    row[5] = e.getJobDesc();
                    row[6] = e.getStatus();
                    row[7] = e.getBackendStatus();
                    
                    jobTableModel.addRow(row);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jobTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        acceptBtn = new javax.swing.JButton();
        rejectBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(240, 233, 152));

        jobTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Department", "Student", "Job ID", "Job Role", "Job Price", "Job Description", "Job Status", "Student Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jobTable);

        jLabel1.setText("Recruit Students for Job");

        acceptBtn.setText("Accept");

        rejectBtn.setText("Reject");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(acceptBtn)
                        .addGap(164, 164, 164)
                        .addComponent(rejectBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel1)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptBtn)
                    .addComponent(rejectBtn))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jobTable;
    private javax.swing.JButton rejectBtn;
    // End of variables declaration//GEN-END:variables
}
